name: Fit Test before merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - shell: cmd
        run: echo startServer.cmd
      - run: cd fit.client
      - run: npm ci
      - run: npm start
