name: Fit Test before merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - shell: cmd
        run: startServer.cmd
      - shell: cmd
      - working-directory: fit.client
        run: npm ci
      - working-directory: fit.client
        run: npm start
